version: 2
jobs:
  job_1:
    docker:
      - image: alpine
    steps:
      - run: echo "In Job_1" 
  job_2: 
    docker:
      - image: alpine
    steps:
      - run: echo "In Job_2 

workflows:
  workflow_1:
    jobs:
      - job_1
      - job_2 
