version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker: 
          version: 17.09.0-ce
      
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-17.09.0-ce.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.09.0-ce.tgz
            tar -xz -C /tmp -f /tmp/docker-17.09.0-ce.tgz
            mv /tmp/docker/* /usr/bin
     
      - run: echo "Docker Installed !" 
